all:
  children:
    proxmox:
      hosts:
        pve:
          ansible_host: 192.168.1.246  # Your Proxmox IP
          ansible_user: root
          ansible_python_interpreter: /opt/proxmoxer_venv/bin/python
